### ISSUE TITLE
Raspberry entrypoint exec format error

### ISSUE THREAD

**Issue by ghost** [hat3ph/adguard-unbound#1]
Hi,

just try to use ur docker but i have this problem :

adguard-unbound    | exec /opt/entrypoint.sh: exec format error

I'm running on " 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux"

What can i do?
Thanks!

EDIT:  I solved it by creating a dockerfile for aarch64

**Comment by hat3ph** [comment]
can you share your dockerfile?

**Comment by ghost** [comment]
Of course,

it's online now

Il giorno 22 apr 2024, alle ore 01:51, hat3ph ***@***.***> ha scritto:


can you share your dockerfile?

**Comment by hat3ph** [comment]
I see you are using arm64v8 alpine linux image but that should be the same as arm64. I am not sure why other different that work for you. Since I do not have any arm based OS to test, if it work for you then good.
If nothing else, I will close this ticket since you have find your solution.
